### ISSUE TITLE
react_async_script_1.default is not a function

### ISSUE THREAD

**Issue by abhirathore2006** [dozoisch/react-async-script#10]
hi, i am using this into a typescript project getting this error.

```
import * as React from "react";
import makeAsyncScriptLoader from "react-async-script";

const callbackName = "onloadcallback";
const URL = `https://maps.googleapis.com/maps/api/js?key=mykey&libraries=places&callback=${callbackName}`;
const globalName = "gmap";

class MapWrapper extends React.Component<{asyncScriptOnLoad?:()=>void},{}>{
  render(){
    return <div></div>
  }
}
export default makeAsyncScriptLoader(MapWrapper, URL, {
  callbackName: callbackName,
  globalName: globalName,
});
```

**Comment by dozoisch** [comment]
Hey! You should checkout the webpack/build tools output you are getting. It seems like the import is not getting resolved properly.

**Comment by dozoisch** [comment]
I'm going to close the issue for now until I have more information from you. The error seems to be on your bundler side, make sure you log the import and check the generated bundle to see what's up with it.
