### ISSUE TITLE
Have babel-runtime as a peer dependency

### ISSUE THREAD

**Issue by lemieux** [dozoisch/react-async-script#11]
Hi,

Would it be possible to have babel-runtime as a peer dependency? I'm currently using 6.9.0 in my project and since this project requires ^5.8.0, I end up with babel-runtime twice in my bundle.

By having it as a peer dep, it would allow developers to provide their own and reuse dependencies.

Thanks!

**Comment by dozoisch** [comment]
Ill try to do it today!

**Comment by lemieux** [comment]
Thanks! I figured after the fact I should have just PR it... sorry about that! Just let me know if you can make it, I'll do it and PR :)

**Comment by dozoisch** [comment]
@lemieux If you can do a pr that would be really helpful!

**Comment by lemieux** [comment]
No problem I'll do it tonight!

**Comment by lemieux** [comment]
Fixed with #12.
