### ISSUE TITLE
Why is babel-runtime a peer dependency ?

### ISSUE THREAD

**Issue by borisirota** [dozoisch/react-async-script#15]
I'm using this module without it.

Thanks

**Comment by dozoisch** [comment]
If you look at the compile source, it uses babel-runtime.

![image](https://cloud.githubusercontent.com/assets/4422516/24595454/9ac1b390-17eb-11e7-91f5-c440f4a006c1.png)

I'm pretty sure one module you are using has bable-runtime as a dependency and it gets pulled in because of that.
