### ISSUE TITLE
React.PropTypes and React.createClass deprecation warning in React 15.5.0

### ISSUE THREAD

**Issue by deificx** [dozoisch/react-async-script#16]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

PropTypes are in the `prop-types` package now and createClass in `create-react-class` so the quick fix is to just add and include from those dependencies. 

https://www.npmjs.com/package/prop-types
https://www.npmjs.com/package/create-react-class

**Comment by dozoisch** [comment]
I'll try to get it done on saturday.

**Comment by dozoisch** [comment]
Fixed in (#18), released in v0.9.0!
