### ISSUE TITLE
how can I use onLoad event when I use react-async-script with react-router

### ISSUE THREAD

**Issue by caolixiang** [dozoisch/react-async-script#3]
Many Thanks.

**Comment by dozoisch** [comment]
Oh yeah didn't get the time to do that readme update.

The actual prop name is `asyncScriptOnload`

see:
https://github.com/dozoisch/react-async-script/issues/2

**Comment by Schmicko** [comment]
FYI - the docs still have a typo.

The prop name is `asyncScriptOnLoad` with a capital L.

https://github.com/dozoisch/react-async-script/blob/master/src/async-script-loader.js#L14
