### ISSUE TITLE
HOC and v1.0.0 release

### ISSUE THREAD

**Issue by hartzis** [dozoisch/react-async-script#33]
- propose turning this into a HOC pattern ✅ 
  - `(options) => (WrapComponent) => WrappedWithAsyncScript`
  - it's so close to being this pattern all ready and is more conducive with community standards. ie. [recompose](https://github.com/acdlite/recompose)
  - example from [this comment](https://github.com/dozoisch/react-async-script/issues/6#issuecomment-155925461) and his re-write in [fork](https://github.com/mikehazell/react-async-script/blob/master/src/async-script-loader.js)
- propose cutting a `v1.0.0` with the above HOC pattern and current options
  - `react-async-script` has been a solid choice in the react community for [years](https://github.com/dozoisch/react-async-script/releases) with a solid API

TODO:
- [x] PR for "standard" HOC pattern
  - #34 
- [x] drop dev support for NODE 4/5/6/7.  No longer LTS. 6 is only maintenance.
  - #36 
- [x] drop option `exposeFuncs` and use `hoist-non-react-statics`
  - #35 
- [x] use `forwardRef` - work started
  - [x] sets peer dep to `"react": ">= 16.3.0"`
  - #37 
- [x] update readme with `migration to 1.0.0` section
  - #40 
- [x] test release candidate with `react-google-recaptcha` - https://github.com/dozoisch/react-google-recaptcha/issues/91
  - Looking good 👍 - Example: https://codesandbox.io/s/1y4zzjq37l

**Comment by dozoisch** [comment]
@hartzis Oh yeah I love this HOC pattern! I'm down.

**Comment by hartzis** [comment]
@dozoisch Thoughts on adding `forwardRef` functionality with the `1.0.0` release?
- https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
- would require peer dep of `"react": ">= 16.3.0"`
  - would then make `react-google-recaptcha@1.0.0` also peer dep on `"react": ">= 16.3.0"`

hrmm.... 🤔 , i'm slightly torn on this one. 

how often and what use cases do you see that users need access to the wrapped components ref instance? it could clean up a bit of `react-google-recaptcha`'s api?

**Comment by hartzis** [comment]
I did some research today and read a few package authors that are trying to stay up with reacts evoIving and growing api and community by adopting new features like `forwardRef.

I like the idea of moving the package forward with react too and using the `forwardRef` api.

The package is still very stable for previous versions of the package and we should continue to link users to previous versions in the readme.

**Comment by dozoisch** [comment]
Alright! Sounds good :)

**Comment by hartzis** [comment]
@dozoisch based on the discussion and confusion in #38 any ideas on how to possibly make it flow better for knowing when a script has/is loaded? i'm starting to question if a HOC is even the right approach.

Examples of other patterns not using a HOC:

children as a function:
```
<AsyncScriptLoader url="www.example.com/js.js" globalName="thing">
  {({ loaded, thing }) => (
    loaded && <ComponentThatNeedsScript thing={thing} />
  )}
</AsyncScriptLoader>
```

Just callback based:
```
<AsyncScriptLoader
  url="www.example.com/js.js"
  asyncScriptOnLoad={() => this.setState({loaded: true})} >
    this.state.loaded && <ComponentThatNeedsScript thing={thing} />
</AsyncScriptLoader>

or doesn't have to wrap

<AsyncScriptLoader
  url="www.example.com/js.js"
  asyncScriptOnLoad={() => this.setState({loaded: true})} />
{this.state.loaded && <ComponentThatNeedsScript thing={thing} />}
```

`AsyncScriptLoader` conditionally renders its children itself based on whether or not the script has loaded?

... thinking of others...

**Comment by hartzis** [comment]
i apologize for the above post if it caused you grief.. lol. I took a walk tonight and started thinking more and i do like the HOC pattern best i think.

I'm curious on your thoughts of having the HOC pass some predefined prop(s) to its wrapped component?
- `scriptLoaded` - *boolean*: if the script has finished loading or not
- `scriptLoading` - *boolean*: if the script is currently loading
- `scriptError` - *string*: if present a string value describing the error

Any/All/None of the above sound interesting/useful?

**Comment by hartzis** [comment]
i'd like to get a v`1.0.0-rc1` release candidate out there soonish so i can start using in codesandbox and maybe get a `react-google-recaptcha` release candidate v`1.0.0` out using this release candidate 😸

**Comment by dozoisch** [comment]
@hartzis I can do a pre-release on npm if you'd like

**Comment by hartzis** [comment]
@dozoisch any thoughts on the additional predefined props? `scriptLoaded`, `scriptLoading`, `scriptError`

we can totally get `1.0.0` out without them since adding them would be backwards compatible 😸 

just need to add a migration guide, but we can also do that after release... I think we can move forward if you want 🎉

**Comment by dozoisch** [comment]
They all sounds pretty useful! Sorry completely missed that message.

**Comment by dozoisch** [comment]
Added the migration notes! After LGTM I'll cut release :)

**Comment by hartzis** [comment]
Rock on!
