### ISSUE TITLE
Use it for OEmbed, it's great, however, I found a weird issue...

### ISSUE THREAD

**Issue by yxwu** [dozoisch/react-async-script#47]
For OEmbed, a js file is used to convert the markup. So I use this package to async load the js. It works when the page get refreshed. But after client navigation,  the markup has NOT been converted by the js, even though the js did get loaded, seems the js doesn't execute.
For both cases, no callback is used.
Any idea? (By the way, I use next.js)

**Comment by yxwu** [comment]
I don't think it's the problem of this loader, most likely the js file doesn't work as expected. So if you close this issue, I am ok.

**Comment by dozoisch** [comment]
@yxwu let me know once you figure out where the issue is (either here or in the JS you load) and I'll close then!

**Comment by yxwu** [comment]
Twitter js can convert the preview markup automatically, while instagram won't. So I call `instgrm.Embeds.process();`
within the asyncScriptOnLoad function, then it works.

Thanks for this great lib.
