### ISSUE TITLE
Feature request: Support script tag attributes

### ISSUE THREAD

**Issue by javidjamae** [dozoisch/react-async-script#51]
I'm integrating with a 3rd party library (OptinMonster) that has a script tag which uses `data-` attributes to customize the script for different customers.

Here is the structure of their script tag:
```
<script type="text/javascript" src="https://a.opmnstr.com/app/js/api.min.js" data-account="12345" data-user="54321" async></script>
```

I looked through the `react-async-script` code and it seems like there is currently no way to provide any optional attributes to the script tag that is generated. 

It would be great if we could provide an optional object of attributes that should be injected into the script tag when generated. 

Something like this:
```
const URL = 'https://a.opmnstr.com/app/js/api.min.js'
const options = {
  tagAttributes: {
    'data-account': '12345',
    'data-user': '54321',
  },
}
makeAsyncScriptLoader(URL, options)(Component)
```

**Comment by dozoisch** [comment]
@javidjamae if you can make a PR for those would be happy to review and cut a release.

**Comment by javidjamae** [comment]
@dozoisch sure, I created PR #52
