### ISSUE TITLE
How we can load more than one script file at once?

### ISSUE THREAD

**Issue by tarkanlar** [dozoisch/react-async-script#8]
Hi,
how we can load more than one script file at once?

**Comment by dozoisch** [comment]
That's a very good question! It's not something that is currently builtin sadly. I'd be open to a PR to be able to have that. Else I'll try to do it when I get some time free.

**Comment by tarkanlar** [comment]
Thanks @dozoisch  :)  for now, i will combine them manually into one file

**Comment by lyquocnam** [comment]
+1
i hope this will be done soon. i really need for that. this is great package.

**Comment by dozoisch** [comment]
@lyquocnam I do accept prs :) I don't have the need for that feature in the things I'm doing right now and do not really have the time to add a new feature

**Comment by dozoisch** [comment]
@lyquocnam  Note that it's possible to do it like this

```
let WrappedRoot = makeAsyncScriptLoader(
  BotRoot,
  'https://cdn.kik.com/kik/2.3.6/kik.js',
  { globalName: 'kik' }
);
WrappedRoot = makeAsyncScriptLoader(
  WrappedRoot,
  'https://maps.googleapis.com/maps/api/js?key=<key>&libraries=places',
  { globalName: 'google' }
);
```

And on load you will get both props
